---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Download Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: yum update
    yum:
      name: '*'
      state: latest
      update_cache: yes

  - name: Install java
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest
      update_cache: yes

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
